package com.salesforce.tests.fs.exception;

public class DirectoryAlreadyExistsException extends RuntimeException {
}
