package com.salesforce.tests.fs.exception;

public class QuitException extends RuntimeException {
}
